title: "Jeongha"
description: "사이트에 대한 간단한 설명을 입력하세요."

author: "박정하"
email: "emilyjungha@gmail.com"

lang: "ko"
timezone: Asia/Seoul
encoding: "utf-8"

url: "https://jeongha-03.github.io"
baseurl: ""

remote_theme: byanko55/jekyll-theme-satellite

logo_img: "/assets/img/favicon.webp"
profile_img: "assets/img/IMG_9857.jpg"

github_username: "jeongha-03"
instagram_username: "__jeongha_"

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "박정하"

markdown: kramdown
highlighter: rouge
permalink: /posts/:year/:month/:day/:title/

kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - README.md
  - "*.sh"

include:
  - _pages
  - .htaccess
